### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by BaguetteYeeter** [bertbert72/HomeAssistant_VirginTivo#103]
The guide says "add to config" but I don't know what config and where

I'm new to Home Assistant and am just trying to add some devices

**Comment by richard-scott** [comment]
The easiest way to install this is via [HACS](https://hacs.xyz/docs/setup/download).

Once you have HACS installed, you can search and add this as an integration. After that, add something like this to your configuration.yaml:

``` yaml
media_player:
  - platform: virgintivo
    force_hd: true
    tvchannellists:
      enable: true
    guide:
      enable_guide: true
    tivos:
      1:
        name: Virgin V6
        host: TIVO.home.lan
```

Obviously, replace the **_TIVO.home.lan_** with the full hostname of your device.

If all that is new to you, look up the following on [YouTube](https://www.youtube.com/watch?v=sVqyDtEjudk). There are also lots of other YouTubers providing content on this subject such as [DrZzs](https://www.youtube.com/channel/UC7G4tLa4Kt6A9e3hJ-HO8ng)
