### ISSUE TITLE
Change to a specific channel using a script?

### ISSUE THREAD

**Issue by BryanChiTown** [bertbert72/HomeAssistant_VirginTivo#105]
Hello! I am new to HA and I was able to set up this integreation for the most part. I wasn't able to figure out how to send commands to specific TiVo's (I have 3), so I removed the other 2 from the list and decided to focus on my main TV. I am trying to set up a script to change the TiVo to a specific channel. I was under the assumption that this was possible as the interface has a drop down of the channels and is updated with the specific channel the TiVo is set to at the moment. However changing the drop down does not change the channel (can't figure that out), and my attempts to send IR or keyboard command via script have been unsuccessful. 

If someone can send me the specific code that I would use to change the TiVo to channel 205 that would be greatly appreciated. My TiVo name is "Living Room" and I am using the device IP to identify it 192.168.1.8

Thank you in advance for your help!

**Comment by TheGosatron** [comment]
Hi! Did you ever find a solution to this? Having the exact same issue, can’t seem to change channels (tried automations, scripts, calling services) nothing seems to work for me). Updates fine, super quick actually, as soon as I change on the remote HA updates instantly. Can send commands like pause just fine, just can’t change the channel. Thanks!

**Comment by richard-scott** [comment]
You need to use the media_player.select_source service call.

**Comment by TheGosatron** [comment]
Thanks yeah I tried that. Nothing in the logs. Other commands work which is strange, can pause and unpause for example. I’ll keep tinkering

**Comment by richard-scott** [comment]
Are you using the channel text rather than the number?
Here is my automation to change to Channel 5 at 6.30am.

```
alias: Change to Channel 5 in the morning.
trigger:
  - at: '06:30:00'
    platform: time
condition: []
action:
  - data:
      entity_id: media_player.virgin_v6
    service: media_player.virgintivo_live_tv
  - delay: '00:00:5'
  - data:
      source: Channel 5
    entity_id: media_player.virgin_v6
    service: media_player.select_source
mode: single
```
