### ISSUE TITLE
DNS Host not working since v0.98 of HA

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#37]
I'm using Home Assistant v0.98.1 and since the 0.98 release I have been unable to use a hostname to find my VirginMedia Tivo.

My config is very simple:

```
- platform: virgintivo
  scan_interval: 3
  tvchannellists:
    enable: true
  tivos:
    1:
      name: Virgin V6
      force_hd: true
      #host: TIVO-C68000022751B8C
      host: 192.168.0.60
```

I have tried both TIVO-C68000022751B8C and TIVO-C68000022751B8C.home.lan for the hostname and neither work. An nslookup on that hostname works fine:

```
root@home-assistant:~# nslookup TIVO-C68000022751B8C
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   TIVO-C68000022751B8C.home.lan
Address: 192.168.0.60
```
