### ISSUE TITLE
virgintivo integration seems to be causing surepetcare integration to fail to start

### ISSUE THREAD

**Issue by badguy99** [bertbert72/HomeAssistant_VirginTivo#46]
Adding the virgintivo media player to my configuration.yaml is causing my surepetcare integration to fail to launch. If I comment out the virgintivo media player, it starts ok.

Configuration:
```
# Sure Petcare products
surepetcare:
  username: <email@example.com>
  password: <password>
  feeders: [1111, 2222]
  flaps: [3333]
  pets: [4444, 5555, 6666, 7777, 8888]

# Virgin Media Tivo
media_player vm_tivo:
  - platform: virgintivo
    scan_interval: 5
    show_packages: Free-to-air,Player,Full House
    tivos:
      1:
        name: Virgin V6
        host: nnn.nnn.nnn.nnn
        force_hd: true
    guide:
      enable_guide: True
      picture_refresh: 60
    tvchannellists:
      enable: True
```

Error in logs:
```
2020-03-08 15:21:52 ERROR (MainThread) [homeassistant.components.surepetcare] Unable to connect to surepetcare.io: Wrong !
2020-03-08 15:21:52 ERROR (MainThread) [homeassistant.setup] Setup failed for surepetcare: Integration failed to initialize.
```

Surepetcare integration code: https://github.com/home-assistant/core/tree/dev/homeassistant/components/surepetcare

System info:
```

arch | aarch64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/London
version | 0.106.5
virtualenv | false

```
