### ISSUE TITLE
BBC One HD (Channel 108) displays as BBC Scotland

### ISSUE THREAD

**Issue by danielsmith89** [bertbert72/HomeAssistant_VirginTivo#53]
<img width="342" alt="Image 2020-05-05 at 9 55 59 am" src="https://user-images.githubusercontent.com/5046816/81049758-ba5bec80-8eb6-11ea-9668-d1048143a837.png">

**Comment by bertbert72** [comment]
That's not actually a defect.  For some insane reason Virgin have different channels for different regions.  So BBC One HD is channel 101 for everywhere apart from England, with 108 being BBC Scotland.  There's no reliable way of working this out from the TV Channel Lists site so the component just works on the first entry for each channel.

To get around it, have a look at example1.yaml in the repository (https://github.com/bertbert72/HomeAssistant_VirginTivo/blob/master/example1.yaml).

Look at the override section and you'll see what you need to put in for BBC One to make it work correctly.

**Comment by danielsmith89** [comment]
Ah, that would explain it!

Thanks for the quick reply and resolution.

**Comment by eyelock** [comment]
This worked for me today:

```
  override:
    101:
      name: BBC One HD
      package: Player
      is_hd: True
    102:
      name: BBC Two HD
      package: Player
      is_hd: True
    103:
      name: STV HD
      package: Player
      is_hd: True
    104:
      name: Channel 4
      package: Player
      is_hd: False
    114:
      name: "STV +1"
      package: Player
      is_hd: False
    141:
      name: Channel 4 HD
      package: Player
      is_hd: True
```
