### ISSUE TITLE
Odd things in source_list

### ISSUE THREAD

**Issue by richard-scott** [bertbert72/HomeAssistant_VirginTivo#60]
There are some odd looking entries in the source_list when you look at the entity state with the HA Developer Tools.
![2020-07-15 16_55_03-Window](https://user-images.githubusercontent.com/5149834/87567597-5b87d000-c6bc-11ea-84ca-52f0d6893618.png)

Here is the relevant exctract from the listings:

![2020-07-15 16_54_44-Window](https://user-images.githubusercontent.com/5149834/87567539-457a0f80-c6bc-11ea-8df9-af7a391d3191.png)

This is my Yaml:
```
- platform: virgintivo
  scan_interval: 5
  force_hd: true
  tvchannellists:
    enable: True
  guide:
    enable_guide: true
  tivos:
    1:
      name: Virgin V6
      host: TIVO-XXXXXXXXXXXX.home.lan
```

There are other odd things in there too, such as:

![2020-07-15 17_01_28-Window](https://user-images.githubusercontent.com/5149834/87567993-d9e47200-c6bc-11ea-9d00-b0b649b3f546.png)
