### ISSUE TITLE
Unique ID Issue

### ISSUE THREAD

**Issue by tombeech** [bertbert72/HomeAssistant_VirginTivo#89]
Hi,

I've installed the addon, it's found my tivo box and I can see it in the GUI, however all i can do it turn it on / off - and when i click settings I get the error:
`
This entity ("media_player.virgin_downstairs") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.`

Would apprecaite any input thanks

Tom

**Comment by bertbert72** [comment]
Can you provide your configuration yaml and log showing any errors?  You can't configure the component via the UI which is why you get that message, only via the yaml.

**Comment by tombeech** [comment]
Hi,

Thanks for that, that makes sense I think. No errors to show, but I can't seem to get anything in the dashboard apart from the power. Even when adding manually. I'm using the default config

```
media_player:
  - platform: virgintivo
    default_is_show: true
    scan_interval: 1
    show_packages: Full House
    tivos:
      1:
        name: Virgin Downstairs
        host: 192.168.50.117
        force_hd: true
        keep_connected: true
    guide:
      picture_refresh: 60
    tvchannellists:
      enable: True
      #url: https://www.tvchannellists.com/List_of_channels_on_Virgin_Media_(UK)
      ignore_channels: 0
      show_channels: 101,102,103,104,105,106,110,115,117,118,121,124,126,127,132,135,139,147,428,875,876
      hide_channels: 990,992,993,994,995,996
      logos:
        875: https://www.freeview.co.uk/app/themes/freeview/assets/images/channels/entertainment/rteone.png
        876: https://www.freeview.co.uk/app/themes/freeview/assets/images/channels/entertainment/rtetwo.png
      targets:
        901: media_player.family_room_receiver
        902: media_player.family_room_receiver
        903: media_player.family_room_receiver
      sources:
        901: Virgin V6
        902: Virgin Tivo
        903: CCTV
      override:
        101:
          name: BBC One
          package: Player
          is_hd: False
        108:
          name: BBC One HD
          package: Player
          is_hd: True
        159:
          name: Liverpool TV
          package: Player
          is_hd: False
        251:
          name: Discovery Channel HD
          package: Full House
          is_hd: True

```

![image](https://user-images.githubusercontent.com/9335109/121784935-ced8e100-cbae-11eb-8828-c38e95b4aabc.png)


![image](https://user-images.githubusercontent.com/9335109/121784948-dc8e6680-cbae-11eb-83ab-aa50dcf78ef4.png)

**Comment by bertbert72** [comment]
That's not really the default config, that's a fairly complex example to show various functions.  Mostly people are better starting off with the real default config and then adding to it, which in your case is:

```
media_player:
  - platform: virgintivo
    tivos:
      1:
        name: Virgin Downstairs
        host: 192.168.50.117
    tvchannellists:
      enable: True
```

The main problem is likely to be the keep_connected switch.  The default for it is false and enabling it without good reason tends to lead to trouble.
